spring:
  application:
    name: core
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
  data:
    redis:
      host: localhost
      port: 6379
      password:

  jpa:
    hibernate:
      ddl-auto: validate # 或 update/create-drop，根据需求
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration






